import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import org.junit.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.support.ui.*;
import org.openqa.selenium.remote.RemoteWebDriver;
import java.net.URL;
import java.net.MalformedURLException;
import pages.*;
import java.util.Random;
import java.io.File;
import org.testng.ITestListener;
import org.testng.ITestResult;
import org.apache.commons.io.FileUtils;

public class SeleniumTester implements ITestListener {

    private WebDriver driver;
    private WebDriverWait wait;

    @Before
    public void setup() throws MalformedURLException, Exception {
        ChromeOptions options = new ChromeOptions();
	options.addArguments("--incognito");
	//options.addArguments("--headless");
        driver = new RemoteWebDriver(new URL("http://selenium:4444/wd/hub"), options);
        driver.manage().window().maximize();

        wait = new WebDriverWait(driver, 10);

	ConfigReader.loadConfig();
    }

    @Test
    public void testLoginLogout() {
	IndexPage ip = new IndexPage(driver, wait);
        Assert.assertTrue(ip.isPageLoaded());
	String username = ConfigReader.getKey("username");
	String password = ConfigReader.getKey("password");
	ip.login(username, password);
	Assert.assertTrue(ip.isLoggedIn(username));
	ip.logout();
	Assert.assertTrue(ip.isLoggedOut());
    }

    @Test
    public void testPodcastHoverColor() {
	IndexPage ip = new IndexPage(driver, wait);
        Assert.assertTrue(ip.checkHoveredPodcastLinkColor());
    }

    @Test
    public void testNavigation() {
	IndexPage ip = new IndexPage(driver, wait);
	ip.navigateToWeatherPage();
	Assert.assertTrue(driver.getTitle().contains("Időjárás"));
	driver.navigate().back();
	Assert.assertFalse(driver.getTitle().contains("Időjárás"));
    }

    @Test
    public void testPageNotFound() {
	// --- Generated by AI ---
	String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();

        int length = 20;

        for (int i = 0; i < length; i++) {
            int index = random.nextInt(chars.length());
            sb.append(chars.charAt(index));
        }
	// --- ---------- ---

	this.driver.get("https://index.hu/" + sb.toString());
	BasePage bp = new BasePage(this.driver, this.wait);
	Assert.assertTrue(bp.waitVisibilityAndFindElement(bp.bodyLocator).getText().contains("Valaki valahol elrontott valamit."));
    }

    @Test
    public void testSessionCookiesClear()
    {
	IndexPage ip = new IndexPage(driver, wait);
        Assert.assertTrue(ip.isPageLoaded());
	String username = ConfigReader.getKey("username");
	String password = ConfigReader.getKey("password");
	ip.login(username, password);
	Assert.assertTrue(ip.isLoggedIn(username));
	driver.manage().deleteAllCookies();
	driver.navigate().refresh();
	ip.clickCookieAccept();
	ip.clickIgnoreButton();
	Assert.assertTrue(ip.isLoggedOut());
    }

    @Override
    public void onTestFailure(ITestResult result) {
        try {
            File src = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
            File dest = new File(result.getName() + ".png");
            FileUtils.copyFile(src, dest);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @After
    public void close() {
        if (driver != null) {
            driver.quit();
        }
    }
}
